
[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3


[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 4
